.PHONY : all

all:
	cc -Wall -Wextra -Wno-format -ggdb3 -fno-delete-null-pointer-checks -fno-isolate-erroneous-paths-dereference -fno-isolate-erroneous-paths-attribute  -O0 main.c
	cc -Wall -Wextra -ggdb3 print_error_values.c -o errvalues
